# 默认配置
server:
  port: 9380
  servlet:
    context-path: /scaffold
spring:
  application:
    name: springboot-scaffold
  profiles:
    active: dev

# mybatis-plus
mybatis-plus:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      table-underline: true
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.leeyom.scaffold.domain.entity

# 监控
javamelody:
  enabled: true
  init-parameters:
    log: true